### ISSUE TITLE
Creating a New Meeting

### ISSUE THREAD

**Issue by Minitour** [shalomweiss/mm-system-2017#26]
## Questions
- What is the exact endpoint for creating a new meeting?
- What are the required/optional parameters?
- What is the response structure?

**Comment by masterFoad** [comment]
* endpoint:
http://zofenweb-env.hhaqjxq9wa.us-east-2.elasticbeanstalk.com/AddMeeting

*parameters:
-required:
id(int), token (String),
 (
Meeting (Object)
*required meeting parameters:
-pairId
-mentorId
-menteeId
-status (must be "PENDING")
-meetingType (PHONE,FACE_TO_FACE,SMS)
-date(long)
-startingDate(long)
-endingDate(long)
-subject
*optional meeting parameters:
-mentorComplete - boolean
-menteeComplete - boolean
-menteeReport
-mentorReport
-menteePrivateReport
-mentorPrivateReport
-location
-note
)



* response structure (json):
code, int
message, String

**Comment by Minitour** [comment]
@masterFoad 

Here is a request body sent to me by @firdos94.
```json
{
	"token": "fCsNKbmzS6FJyqTuRANhd2nrAYSa6juOmimKeA0JuxPetBrfVpyYPBsKlptcqMo9GwV0UmSfS5YewXJaDp4cLNfpyd3TbcZjrMXNjQ6pKhl95EhVFNxCWGmSvBbm7UJV",
	"id": 16,
	"meeting": {
            "pairId":2,
            "mentorId":17,
            "menteeId":16,
            "status":"APPROVED",
            "meetingType":"FACE_TO_FACE",
            "mentorComplete":false,
            "menteeComplete":false,
            "date":10,
            "startingDate":1000,
            "endingDate":10000000,
            "subject":"the subject of debugging",
            "location":"citadel.."
    }
}
```
**Few Notes:**
- We don't have the `pairId`.
- We also agreed that the only the mentor can create a meeting therefore there is no need to include `mentorId` inside the meeting body since it's specified in the request as `id`.
- We also don't need to send out the `status` field since it is automatically changed by the system.
- As well as the `mentorComplete` and `menteeComplete`. These are set by the system as well.

**Finally we end up with a request body like this:**
```json
{
   "id" : 17,
   "token" : "...",
  "meeting" : {
        "menteeId" : 16,
        "meetingType":"FACE_TO_FACE",
        "date": value,
        "startingDate": value,
        "endingDate": value,
        "subject":"the subject of debugging",
        "location":"somewhere"
   }
}
```

**Comment by masterFoad** [comment]
the pairId is included with the meeting, when you run the GetMeetings request.
I will change and update you.

**Comment by masterFoad** [comment]
@Minitour

**Comment by Minitour** [comment]
@masterFoad What if It is the first meeting that I am adding? this means I don't have the `pairId`. besides it's a bad practice to send the `pairId` in the request. What if I submit a false `pairId`?
The `pairId` should be extracted based on the `mentorId` and the `menteeId`.

**Comment by masterFoad** [comment]
@Minitour you are right, can you tell me more about the AddMeeting screen you have?
will adding a new separate servlet that get the pairId given the Mentor and the mentee's id solve the problem?

**Comment by Minitour** [comment]
@masterFoad Trying to keep it simple. Here is a screenshot of the work in progress:

<img width="320" alt="screen shot 2017-10-13 at 17 15 05" src="https://user-images.githubusercontent.com/17438617/31550475-1d8b570e-b03a-11e7-9f68-19425308f4d0.png">

**Comment by masterFoad** [comment]
@Minitour when you open this screen, you will get the pairId from a servlet that we will create, then you can use it.
Good?

**Comment by Minitour** [comment]
@masterFoad 
We can do that but I would prefer that the pairId would not be sent from the frontend.

**Comment by masterFoad** [comment]
I understand, then you only send the id's.

**Comment by Minitour** [comment]
@masterFoad Make sure to notify me when the changes has been made and are uploaded to the server so we can test it.

**Comment by masterFoad** [comment]
@NajibAbuSamra Still waiting for the getPairId

**Comment by NajibAbuSamra** [comment]
implemented and pushed

**Comment by masterFoad** [comment]
AddMeeting is working, Will deploy soon.

**Comment by Minitour** [comment]
I will keep the issue open until I test it on the Android client.

**Comment by masterFoad** [comment]
@Minitour 
My test:
```json
{
	"meeting": {
          "menteeId":16,
              "meetingType":"FACE_TO_FACE",
                    "date":10,
                      "startingDate":1000,
                        "endingDate":10000000,
                          "subject":"is it working????"

    }
	"token": "fCsNKbmzS6FJyqTuRANhd2nrAYSa6juOmimKeA0JuxPetBrfVpyYPBsKlptcqMo9GwV0UmSfS5YewXJaDp4cLNfpyd3TbcZjrMXNjQ6pKhl95EhVFNxCWGmSvBbm7UJV",
	"id": 17
}
```

**Comment by Minitour** [comment]
@masterFoad is it possible not to send the `date` field? instead can you extract it from the `startingDate`?

Since the `startingDate` is a timestamp you can do the following:
```java
Calendar calendar = Calendar.getInstance();
calendar.setTimeInMillis(timeStamp);

int mYear = calendar.get(Calendar.YEAR);
int mMonth = calendar.get(Calendar.MONTH);
int mDay = calendar.get(Calendar.DAY_OF_MONTH);
```

I would like the request format to be as follows:
```json
{
  "token": "iuqOxmaHidXgFNuqINBVZFMfRf9G5nN7TY4nN6goVceIGFLDPAcPFj29ER3uLCPO44jRsXZIeQB9DQrNSszS1zcEJHOHHRDMloVCEDHUOlLMpfPvEUteJj4gfnMWyJTf",
  "id": 17,
  "meeting": {
    "startingDate": 1508103000000,
    "subject": "How to properly use Git",
    "endingDate": 1508106600000,
    "location": "The university",
    "menteeId": 16,
    "meetingType": "FACE_TO_FACE"
  }
}
```

**Comment by masterFoad** [comment]
@Minitour Done.

**Comment by masterFoad** [comment]
@Minitour 
A valid session token to use for tests:

	"meeting": {
          "menteeId":16,
              "meetingType":"FACE_TO_FACE",
                      "startingDate":1508103000000,
                        "endingDate":1508106600000,
                          "subject":"git"

    },
	"token": "AAsNKbmzS6FJyqTuRANhd2nrAYSa6juOmimKeA0JuxPetBrfVpyYPBsKlptcqMo9GwV0UmSfS5YewXJaDp4cLNfpyd3TbcZjrMXNjQ6pKhl95EhVFNxCWGmSvBbm7UJV",
	"id": 17
}

**Comment by Minitour** [comment]
@masterFoad I hope you are consuming the `location` parameter as well.
