### ISSUE TITLE
Improving Error Handling

### ISSUE THREAD

**Issue by Minitour** [shalomweiss/mm-system-2017#28]
I noticed that in most servlets, if a parameter is missing then the server would throw an exception with an HTML message. Although it is a good idea for GET requests, It is not a good practice to return HTML in for POST requests, Therefor I suggest that all the code in all the POST servlets will be wrapped in the following format:

```java

protected void doPost(HttpServletRequest req, HttpServletResponse res) {
     final AndroidIOManager iom = new AndroidIOManager(req,res);
     try{
           
           /**
            *   Apply Servlet Logic Here
            **/

     }catch(NullPointerException ex){
             iom.setResponseMessage(new RESPONSE_STATUS(RESPONSE_STATUS.PARAM_FAILED))
     }catch(Exception e){
             iom.setResponseMessage(new RESPONSE_STATUS(RESPONSE_STATUS.UNKNOWN))
     }finally{
             iom.SendJsonResponse();
     }
}
```

**Comment by masterFoad** [comment]
@Minitour you are right, on it.

**Comment by firdos94** [comment]
@masterFoad @Minitour  is still relevant?

**Comment by Minitour** [comment]
@firdos94 
@masterFoad 
If you are following this pattern in all servlets then we can close this issue.

**Comment by masterFoad** [comment]
@Minitour @firdos94 @NajibAbuSamra 
You can close.
