### ISSUE TITLE
Unhandled Exception in ApproveMeeting

### ISSUE THREAD

**Issue by Minitour** [shalomweiss/mm-system-2017#29]
https://github.com/shalomweiss/mm-system-2017/blob/e2896abc8762ac4dec3f556f07217d8088f002d9/src/mm/androidservice/ApproveMeeting.java#L60

A response is missing in the catch block.
```java
catch (NumberFormatException | SQLException e) {
      // TODO Auto-generated catch block
      e.printStackTrace();
      iom.setResponseMessage(new RESPONSE_STATUS(RESPONSE_STATUS.PARAM_FAILED));
}

```

**Comment by Minitour** [comment]
@masterFoad Might as well remove the inner `try-catch` since you added an outer one.

**Comment by masterFoad** [comment]
@Minitour 1 moment.

**Comment by masterFoad** [comment]
@Minitour  BTW, addmeeting still needs the getPairId method. 
@NajibAbuSamra

**Comment by Minitour** [comment]
@masterFoad we should discuss that on issue #26

**Comment by masterFoad** [comment]
@Minitour Done.
