### ISSUE TITLE
New API: Cancel Meeting

### ISSUE THREAD

**Issue by Minitour** [shalomweiss/mm-system-2017#30]
## Description
The issue was brought up in issue #27. We need an API to cancel an `APPROVED` meeting.
This action can be preformed by both the mentor and the mentee.

- This only applies to meetings that are `APPROVED` or `PENDING`.
- If the meeting is `PENDING` then this action can only be preformed by the mentor.
- If the meeting is `APPROVED` then this action can be preformed by both the mentor and mentee.

## Endpoint
```
/CancelMeeting
```
## Request Body
```json
{
"id" : "1",
"token" : "myAuthToken",
"meetingId" : 1,
"message" : "The reason for which the meeting is being cancelled."
}
```

## Response
```json
{
"code" : 200,
"message" : "success"
}
```

**Comment by Minitour** [comment]
The `message` parameter in the request will be inserted into the `notes` field in the database.

**Comment by NajibAbuSamra** [comment]
I see we have yet to implement adding mentor/mentee notes (both public and private) to meetings, I will get to it now
