### ISSUE TITLE
Add Logo of the mentor program

### ISSUE THREAD

**Issue by NajibAbuSamra** [shalomweiss/mm-system-2017#44]
*discussion here*

close when finished

**Comment by danielzar2710** [comment]
@masterFoad @firdos94 please upload logo pic on server and give path

**Comment by NajibAbuSamra** [comment]
can I have an update on the status of this task?

**Comment by firdos94** [comment]
@masterFoad can we add logo pic to package of images in amazon (the same package for users's profile pic )?

**Comment by masterFoad** [comment]
Someone send me the logo please


@firdos94 @danielzar2710
