### ISSUE TITLE
gitignore update -- .json

### ISSUE THREAD

**Issue by masterFoad** [shalomweiss/mm-system-2017#49]
@NajibAbuSamra  we need to add .json to gitignore.

**Comment by firdos94** [comment]
the key is not working at the moment, does not the json contain something ?

**Comment by masterFoad** [comment]
@firdos94  I sent the key by mail. 
add them to the json file manually. (Be careful not to push until Najib add to gitignore)

**Comment by firdos94** [comment]
we are setting with nagib now.

**Comment by NajibAbuSamra** [comment]
I have introduced the required change (I hope)

Please confirm you don't see the file in your change list after updating with the proper keys

**Comment by masterFoad** [comment]
@firdos94 @NajibAbuSamra @danielzar2710 added resources folder+instructions just for validation.
