### ISSUE TITLE
implemented connection pooling

### ISSUE THREAD

**Issue by masterFoad** [shalomweiss/mm-system-2017#55]
@NajibAbuSamra 
Close connection in DataAccess
I have implemented Connection Pooling to fix various connection problems, I think now you have to close every connection in every sql query, not only the statement and resultset, but also the conn.

when you get my version, Don't forget to change the parameters in the context.xml
I have attached them in email.

@NajibAbuSamra  add context.xml to gitignore

**Comment by NajibAbuSamra** [comment]
I will add it after the merge, I left a review on your pull request

**Comment by NajibAbuSamra** [comment]
> not only the statement and resultset, but also the conn.

yes, we (me and @firdos94 ) came to that conclusion too, but still not sure who should close the connection, as the connection is opened when the DA is created in the server when a servlet is called. 

your thoughts @masterFoad ?

**Comment by masterFoad** [comment]
@NajibAbuSamra 
For example in every method in DA:
`public User login(String email) throws SQLException {
		Logger logger = Logger.getLogger(DataAccess.class.getName());
		if (c == null) {
			logger.log(Level.SEVERE, "Connection Failed");
			return null;
		}
		PreparedStatement stm = c
				.prepareStatement(SQLStatements.selectUserByEmail);
		stm.setString(1, email);

		ResultSet rs = stm.executeQuery();
		User u = null;
		if (rs.next()) {
			int type = rs.getInt(DataContract.UsersTable.COL_TYPE);
			switch (type) {

			case 0: // Admin
				logger.log(Level.WARNING,
						"User type Admin, no admins exist in the system at this time");
				break;
			case 1: // Tsofen member
				logger.log(Level.INFO, "User type Tsofen");
				u = new TsofenT(
						rs.getInt(DataContract.UsersTable.COL_ID),
						rs.getString(DataContract.UsersTable.COL_FIRSTNAME),
						rs.getString(DataContract.UsersTable.COL_LASTNAME),
						rs.getString(DataContract.UsersTable.COL_EMAIL),
						rs.getString(DataContract.UsersTable.COL_PHONENUMBER),
						rs.getString(DataContract.UsersTable.COL_PASSWORD),
						rs.getInt(DataContract.UsersTable.COL_GENDER),
						rs.getString(DataContract.UsersTable.COL_ADDRESS),
						rs.getString(DataContract.UsersTable.COL_NOTES),
						rs.getString(DataContract.UsersTable.COL_PROFILEPICTURE),
						rs.getBoolean(DataContract.UsersTable.COL_ACTIVE),
						userType.TSOFEN);
				break;
			case 2:// Mentor
				logger.log(Level.INFO, "User type Mentor");
				PreparedStatement stm2 = c
						.prepareStatement(SQLStatements.selectMentorById);
				stm2.setInt(1, rs.getInt(DataContract.MentorsTable.COL_ID));

				ResultSet rs2 = stm2.executeQuery();
				if (rs2.next())
					u = new Mentor(
							rs.getInt(DataContract.UsersTable.COL_ID),
							rs.getString(DataContract.UsersTable.COL_FIRSTNAME),
							rs.getString(DataContract.UsersTable.COL_LASTNAME),
							rs.getString(DataContract.UsersTable.COL_EMAIL),
							rs.getString(DataContract.UsersTable.COL_PHONENUMBER),
							rs.getString(DataContract.UsersTable.COL_PASSWORD),
							rs.getInt(DataContract.UsersTable.COL_GENDER),
							rs.getString(DataContract.UsersTable.COL_ADDRESS),
							rs.getString(DataContract.UsersTable.COL_NOTES),
							rs.getString(DataContract.UsersTable.COL_PROFILEPICTURE),
							rs.getBoolean(DataContract.UsersTable.COL_ACTIVE),
							userType.MENTOR,
							rs2.getString(DataContract.MentorsTable.COL_EXPERIENCE),
							rs2.getString(DataContract.MentorsTable.COL_ROLE),
							rs2.getInt(DataContract.MentorsTable.COL_COMPANY),
							rs2.getString(DataContract.MentorsTable.COL_VOLUNTEERING),
							rs2.getString(DataContract.MentorsTable.COL_WORKHISTORY));
				rs2.close();
				stm2.close();
				break;
			case 3:// Mentee
				logger.log(Level.INFO, "User type Mentee");
				PreparedStatement stm3 = c
						.prepareStatement(SQLStatements.selectMenteeById);
				stm3.setInt(1, rs.getInt(DataContract.MenteeTable.COL_ID));

				ResultSet rs3 = stm3.executeQuery();
				if (rs3.next())
					u = new Mentee(
							rs.getInt(DataContract.UsersTable.COL_ID),
							rs.getString(DataContract.UsersTable.COL_FIRSTNAME),
							rs.getString(DataContract.UsersTable.COL_LASTNAME),
							rs.getString(DataContract.UsersTable.COL_EMAIL),
							rs.getString(DataContract.UsersTable.COL_PHONENUMBER),
							rs.getString(DataContract.UsersTable.COL_PASSWORD),
							rs.getInt(DataContract.UsersTable.COL_GENDER),
							rs.getString(DataContract.UsersTable.COL_ADDRESS),
							rs.getString(DataContract.UsersTable.COL_PROFILEPICTURE),
							rs.getString(DataContract.UsersTable.COL_NOTES),
							rs.getBoolean(DataContract.UsersTable.COL_ACTIVE),
							userType.MENTEE,
							rs3.getFloat(DataContract.MenteeTable.COL_REMAININGSEMESTERS),
							rs3.getString(DataContract.MenteeTable.COL_GRADUATIONSTATUS),
							rs3.getInt(DataContract.MenteeTable.COL_ACADEMICINSTITUTE),
							rs3.getFloat(DataContract.MenteeTable.COL_AVERAGE),
							rs3.getString(DataContract.MenteeTable.COL_ACADEMICDICIPLINE1),
							rs3.getString(DataContract.MenteeTable.COL_ACADEMICDICIPLINE2),
							rs3.getBoolean(DataContract.MenteeTable.COL_SIGNEDEULA),
							rs3.getString(DataContract.MenteeTable.COL_RESUME),
							rs3.getString(DataContract.MenteeTable.COL_GRADESHEET));
				break;

			default:
				logger.log(Level.WARNING, "User type unknown");
				break;
			}
		}

		rs.close();
		stm.close();

<ADD --> 

c.close();

		return u;
	}`

**Comment by NajibAbuSamra** [comment]
yes, but this could cause a problem if in a servlet there are more than one DA method being called, as in the methods we don't start not check the connection 😄 the only one who knows when we're  "done" is the server when the servlet has finished its task

**Comment by masterFoad** [comment]
this is the reason I implemented the connection pool, when you close a connection you only return it to the pool.

**Comment by NajibAbuSamra** [comment]
ok, I will work on it now. I added the ignore rule for the xml directly into main, so everything should be ready for other people to continue work (as in change the xml file manually but not affect the github file)

**Comment by masterFoad** [comment]
I have changed DBUtil to singleton and fixed init set up.
I will push to main

**Comment by masterFoad** [comment]
@NajibAbuSamra I think a better solution would be to call in the close connection in servlets instead in the DA itself, when the servlet finish the DA requests, it should close the connection.
I can add this to all android servlets quickly. @firdos94 should add the close to the web servlets.

**Comment by masterFoad** [comment]
@NajibAbuSamra you only need to add a close connection method to the da.

**Comment by masterFoad** [comment]
update  - added closeConnection() method to android servlets.

**Comment by NajibAbuSamra** [comment]
> @NajibAbuSamra you only need to add a close connection method to the da.

I have been adding close connection to all the methods for the past hour 😢 should I remove them?

**Comment by masterFoad** [comment]
@NajibAbuSamra yes please :/

**Comment by NajibAbuSamra** [comment]
I reverted all changes until your merge is finished

**Comment by masterFoad** [comment]
sorry, I should have said earlier.

**Comment by NajibAbuSamra** [comment]
Connections seem to be working properly now, closing issue.
