### ISSUE TITLE
connection problems

### ISSUE THREAD

**Issue by danielzar2710** [shalomweiss/mm-system-2017#67]
INFO: Reloading Context with name [/mm-database-2017] has started
Nov 08, 2017 11:42:54 AM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesJdbc
WARNING: The web application [mm-database-2017] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Nov 08, 2017 11:42:54 AM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
WARNING: The web application [mm-database-2017] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.ref.ReferenceQueue.remove(Unknown Source)
 com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:64)
 java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 java.lang.Thread.run(Unknown Source)
Nov 08, 2017 11:42:56 AM org.apache.catalina.loader.WebappClassLoaderBase checkStateForResourceLoading
INFO: Illegal access: this web application instance has been stopped already. Could not load []. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load []. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1359)
	at org.apache.catalina.loader.WebappClassLoaderBase.getResource(WebappClassLoaderBase.java:1029)
	at com.mysql.jdbc.AbandonedConnectionCleanupThread.checkContextClassLoaders(AbandonedConnectionCleanupThread.java:90)
	at com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Nov 08, 2017 11:43:00 AM org.apache.tomcat.dbcp.dbcp2.BasicDataSourceFactory getObjectInstance
WARNING: Name = UsersDB Property maxActive is not used in DBCP2, use maxTotal instead. maxTotal default value is 8. You have set value of "10" for "maxActive" property, which is being ignored.
Nov 08, 2017 11:43:00 AM org.apache.tomcat.dbcp.dbcp2.BasicDataSourceFactory getObjectInstance
WARNING: Name = UsersDB Property maxWait is not used in DBCP2 , use maxWaitMillis instead. maxWaitMillis default value is -1. You have set value of "10000" for "maxWait" property, which is being ignored.
Nov 08, 2017 11:43:00 AM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Nov 08, 2017 11:43:00 AM org.apache.catalina.core.StandardContext reload
INFO: Reloading Context with name [/mm-database-2017] is completed
![image](https://user-images.githubusercontent.com/26320595/32542100-46d1b99c-c47a-11e7-8990-6e530fa6e331.png)

**Comment by danielzar2710** [comment]
@NajibAbuSamra  @masterFoad 
I clicked F5 to reload Mentee page and it has shown me this mistake (I do not think it is related to thementee page because i have seen it before).

**Comment by masterFoad** [comment]
@danielzar2710 on it.

**Comment by NajibAbuSamra** [comment]
@danielzar2710 when this error happens, can you continue your work does it cause a visible error on screen?

**Comment by danielzar2710** [comment]
no it does not prevent me from doing anything but it might be a security breach we should look into in the future

**Comment by masterFoad** [comment]
@NajibAbuSamra you can close.
