### ISSUE TITLE
new Milestone suggestion

### ISSUE THREAD

**Issue by danielzar2710** [shalomweiss/mm-system-2017#69]
After completing the first milestone we should agree on the next one.
I suggest the following tasks:
1.add id to each user (israeli id).
2. Make the reports work
3. Support adding city/ area / company / academy.
Do you think it is fine for the second milestone?

**Comment by danielzar2710** [comment]
@NajibAbuSamra @firdos94 @masterFoad

**Comment by NajibAbuSamra** [comment]
I think it's fine, but we still have other things that require attention first, reports are indeed the main thing but will be better to work on them after the rest of the system is "stable" (i.e. no new information being added to the models)

for now I have marked several items on the google sheet shalom prepared with our tasks, please review it and tell me which tasks were already finished:

1) Add ending date to ....
2) Dropbox should be Decline ....
3) In the Pairs screen add more details (full name, "Working place", "learning Institute", phones)
4) Add field "if a new meeting was created"
5) Add a field for the last meeting and if the Pairs finish their work together
6) Database connection (**might be already finished, but I don't think we tested it properly**)
7) Hash Passwords before storing in db
8) add id to each user (israeli id)
9) synch coloring between the android and the web (@Minitour **haven't seen any android screen in weeks** )
10) When a Mentee is open his Adroid application he/she need to cv (if there isn't)
11) Check if session is valid (**might be already finished**)

**Comment by danielzar2710** [comment]
"Add ending date to ...." 
"Dropbox should be Decline ..."
what does all of them mean mean?

Q.Check if session is valid (might be already finished) ?
A.No

**Comment by danielzar2710** [comment]
In the Pairs screen add more details (full name, "Working place", "learning Institute", phones): Done

**Comment by danielzar2710** [comment]
For most of those tasks we will need some meetings to be created

**Comment by NajibAbuSamra** [comment]
We will discuss these on monday 10:30 (or after)

**Comment by danielzar2710** [comment]
The things we have to do:

1.Add ending date to .... - 
2.Add field "if a new meeting was created"
3.create a field for a pair :"have they finished their work together".
4.Add activate (the opposite of deactivate function) function for user or pair.
5.Database connection (might be already finished, but I don't think we tested it properly)
6.Hash Passwords before storing in db
7.add id to each user (israeli id)
8.synch coloring between the android and the web (@Minitour haven't seen any android screen in weeks )
9.When a Mentee is open his Adroid application he/she need to cv (if there isn't)
10.Check if session is valid (might be already finished)
11.We need to support file uploading (like gradesheets and cv) for the web
12.Support the question:"does have a cv"
@NajibAbuSamra 
@firdos94 
@masterFoad 
@Minitour
