### ISSUE TITLE
reactivate user

### ISSUE THREAD

**Issue by firdos94** [shalomweiss/mm-system-2017#76]
needed a new database function: boolean activateUser(int id)
@NajibAbuSamra @danielzar2710 .

**Comment by NajibAbuSamra** [comment]
added directly to main (oops) you can now user the method activateUser(id)

**Comment by firdos94** [comment]
added, @danielzar2710 check that it's works fine to close this issue

**Comment by danielzar2710** [comment]
checking

**Comment by danielzar2710** [comment]
works
