### ISSUE TITLE
add working palce does not work

### ISSUE THREAD

**Issue by danielzar2710** [shalomweiss/mm-system-2017#77]
add working palce does not work
![image](https://user-images.githubusercontent.com/26320595/33176663-808907fe-d068-11e7-8957-421e027083bb.png)

**Comment by danielzar2710** [comment]
@NajibAbuSamra @firdos94

**Comment by NajibAbuSamra** [comment]
Worked with daniel, fixed the issue, parameter name did not match what web sent and what servlet was expecting
