### ISSUE TITLE
File Upload seems to work but File Download always responds with an empty file.

### ISSUE THREAD

**Issue by Minitour** [shalomweiss/mm-system-2017#78]
For example:
http://zofenweb-env.hhaqjxq9wa.us-east-2.elasticbeanstalk.com:80/DownloadFile?img=208 

I am logged in as user 208 and I uploaded a profile picture. It returned code 200, but when trying to download the image I get a file with content length 0.

**Comment by NajibAbuSamra** [comment]
I just checked the sql tables, the user 208 (daniel) does not have a link to the profile picture saved in the db.

**Comment by NajibAbuSamra** [comment]
Are we even saving the link to the users' pictures in the db?

**Comment by masterFoad** [comment]
@NajibAbuSamra no we are not

**Comment by NajibAbuSamra** [comment]
ok...

**Comment by NajibAbuSamra** [comment]
is this still an issue? @masterFoad

**Comment by masterFoad** [comment]
@NajibAbuSamra you can close.
